### ISSUE TITLE
Wrong client timestamp

### ISSUE THREAD

**Issue by bovy89** [sensu/uchiwa#456]
Hi,
the timestamp retrieved from sensu api, seems to be not correct.

If i interrogate sensu-api directly with my browser, i obtain something like 1457037509 as timestamp.

I inspected the response in Uchiwa with firebug and i obtain something like 1.457035675e+09.

The value 1457037509 is correct and the label indicates "a few second ago"; the value 1.457035675e+09 instead indicates "25 minute ago".

Sensu version: 0.22.0

Uchiwa version: 0.14.2

**Comment by dmichelotto** [comment]
+1

**Comment by kaos** [comment]
Is it correct on the /clients page, but not on the detail page for the client?
If so, you've hit a bug which I've addressed in PR sensu/uchiwa-web#93: https://github.com/sensu/uchiwa-web/pull/93/commits/da1fb63b5583fadc87cb3876232ca56a1285a7c1

And it's not the raw timestamp value that is wrong.. it is how it is presented, in that case.

**Comment by bovy89** [comment]
This bug still exists:

Release 0.13 (correct)
![013_img1](https://cloud.githubusercontent.com/assets/697408/16491594/db59839c-3ede-11e6-817c-3906ec8aa93d.png)
![013_img2](https://cloud.githubusercontent.com/assets/697408/16491593/db582cfe-3ede-11e6-8e15-e81224cc9d10.png)

Release > 0.13 (bugged)
![016_img1](https://cloud.githubusercontent.com/assets/697408/16491591/db3acfe2-3ede-11e6-9ad5-10ee956902c1.png)
![016_img2](https://cloud.githubusercontent.com/assets/697408/16491592/db5183ae-3ede-11e6-95aa-449cf4da7f4a.png)
